create database hito3_2023;
use hito3_2023;
##======================LABS 3============================##
#SUBSTRING CORTA LA CADENA
#BDAII 2023 Unifranz
#2023
#SELECT substring(cadena,start,length);
#SELECT substring(cadena from start for length);
#CONTANDO DESDE IZQUIERDA
SELECT substring('DBAII 2023 Unifranz', 7);
SELECT substring('DBAII 2023 Unifranz', 7,4);
#para que lea de DERECHA a IZQUERDA se usa -
SELECT substring('DBAII 2023 Unifranz',-8);
SELECT substring('DBAII 2023 Unifranz',-13,4);
SELECT substring('DBAII 2023 Unifranz',1,1);
SELECT substring('DBAII 2023 Unifranz' from 7 for 4);
SELECT substring('HOLA', 3);
#MANDEJO DE DATOS
#BASE DE DATOS II, GESTION 2023 UNIFRANZ
#SI QUEREMOS BUSCAR 2023 NECESITAMOS 27
#LOCATE= PERMITE BUSCAR UNA CADENA
#SELECT LOCATE(LA PALABRA A BUSCAR,CADENA)
SELECT LOCATE('2023','BASE DE DATOS II, GESTION 2023 UNIFRANZ');
#PARA BUSCAR DESDE UNA POSICION LA PALABRA DECEADA
SELECT LOCATE('2023','BASE DE DATOS II, GESTION 2023 UNIFRANZ 2023',30);
#CREAR UNA FUNCION QUE RECIBA 2 PARAMETROS "6993499LP","LP"
#VERIFICAR SI EXISTE EN LA CADENA
# SI EXISTE RETURNA UN MENSAJE: SI EXISTE; POSICION
# SI NO EXISTE RETORNAR: NO EXISTE
CREATE OR REPLACE FUNCTION LOCATE1(CADENA TEXT,CADENA2 TEXT)
RETURNS TEXT
BEGIN
    DECLARE RESP TEXT DEFAULT '';
    DECLARE A INT DEFAULT LOCATE(CADENA2,CADENA);
    IF  LOCATE(CADENA2,CADENA) > 0 THEN
        SET RESP=CONCAT('SI EXISTE: ',A);
    ELSE SET RESP = 'NO EXISTE';
    END IF;
    RETURN RESP;
end;
SELECT LOCATE1('6993499LP','LP');
#CREAR UNA FUNCION QUE RECIBA UN PARAMETRO INTEGER
#EN DONDE ESTE PARAMETRO DEBERA DE RECIBIR UN VALOR NUMERICO
#EJERICIO 1
CREATE OR REPLACE FUNCTION NUMEROSNATURALESV2(LIMITE INT)
RETURNS TEXT
BEGIN
    DECLARE RESP TEXT DEFAULT '';
    DECLARE CONT INT DEFAULT 0;
   WHILE CONT <= LIMITE DO
       SET RESP = CONCAT(RESP,CONT,',');
       SET CONT = CONT + 2;
       end while;
    RETURN RESP;
end;
SELECT NUMEROSNATURALESV2(10);
#CREAR FUNCION QUE RECIBA 2 PARAMETROS
CREATE OR REPLACE FUNCTION CONCATENARTEXTNUMv2(CADENA TEXT,x INT)
RETURNS TEXT
BEGIN
   DECLARE str TEXT DEFAULT '';
   DECLARE aux int DEFAULT 0;
   repeat
       set str = CONCAT(str,CADENA,'-');
        set aux = aux + 1;
        until aux = x
     end repeat;
   RETURN str;
end;
SELECT CONCATENARTEXTNUMv2('BDAII',5);