create database hito3_2023;
use hito3_2023;
#CREACION DE VARIABLES MYSQL ES MULTIUSUARIO Y CADA USUARIO PUEDE CREAR SU PROPIA VARIABLE
#USANDO SET, LA VARIABLE CREADA SOLO ESTA EN ESA BASE DE DATO
SET @USUARIO = 'GUEST';
SET @LOCACION = 'EL ALTO';
SET @hito3 = 'ADMIN';

SELECT @USUARIO;
SELECT @LOCACION;

CREATE OR REPLACE FUNCTION VARIABLE()
RETURNS TEXT
BEGIN
    RETURN @USUARIO;
end;
SELECT VARIABLE();
#CREAR UNA VARIABLE DE NOMBRE GLOBAL DE NOMBRE HITO3
#A ESTA VARIABLE ASIGNARLE EL VALOR ADMIN
#CREAR U8NA FUNCION QUE MANEJE ESTA VARIABLE GLOBAL
#SI EL VALOR DE LA VARIBALE GLOBAL ES ADMIN
#RETORNA UN MENSAJE QUE DIGA. "USUARIO ADMIN"
#SI ES DISTINTO DE ADMIN, RETORNAN EL MENSAJE "USUARIO UNVITADO"

CREATE OR REPLACE FUNCTION VARIABLE2()
RETURNS TEXT
BEGIN
    DECLARE RESP TEXT;
    IF @hito3 = 'ADMIN' then
       SET RESP = 'usuario ADMIN';
end if;
    IF @hito3 != 'ADMIN' then
      SET RESP = 'usuario INVITADO';
end if;
    RETURN RESP;
end;
SELECT VARIABLE2();

CREATE OR REPLACE FUNCTION VARIABLEV3()
RETURNS TEXT
BEGIN
    DECLARE RESP TEXT;
    CASE
        WHEN @hito3 = 'ADMIN' then
            SET RESP = 'usuario ADMIN';
        ELSE
            SET RESP = 'usuario INVITADO';
    END CASE;
    RETURN RESP;
end;
SELECT VARIABLEV3();
#GENERAR LOS PRIEMROS 10 NUMEROS NATURALES
CREATE OR REPLACE FUNCTION NUMEROSNATURALES(LIMITE INT)
RETURNS TEXT
BEGIN
    DECLARE RESP TEXT DEFAULT '';
    DECLARE CONT INT DEFAULT 1;
   WHILE CONT <= LIMITE DO
       SET RESP = CONCAT(RESP,CONT,',');
       SET CONT = CONT + 1;
       end while;
    RETURN RESP;
end;
SELECT NUMEROSNATURALES(10);
#V2
CREATE OR REPLACE FUNCTION NUMEROSNATURALESV2(LIMITE INT)
RETURNS TEXT
BEGIN
    DECLARE RESP TEXT DEFAULT '';
    DECLARE CONT INT DEFAULT 2;
   WHILE CONT <= LIMITE DO
       SET RESP = CONCAT(RESP,CONT,',');
       SET CONT = CONT + 2;
       end while;
    RETURN RESP;
end;
SELECT NUMEROSNATURALESV2(10);
#EJERICIO 1
CREATE OR REPLACE FUNCTION NUMEROSNATURALESV3(LIMITE INT)
RETURNS TEXT
BEGIN

    DECLARE RESP TEXT DEFAULT '';
    DECLARE CONT INT DEFAULT 2;
    DECLARE CONT2 INT DEFAULT 1;
   WHILE CONT <= LIMITE DO
       SET RESP = CONCAT(RESP,CONT,',',CONT2,',');
       SET CONT = CONT + 2;
       SET CONT2 = CONT2 + 2;
       end while;
    RETURN RESP;
end;

SELECT NUMEROSNATURALESV3(10);

#VERSION DEL ING
CREATE OR REPLACE FUNCTION NUMEROSNATURALESV4(LIMITE INT)
RETURNS TEXT
BEGIN

    DECLARE RESP TEXT DEFAULT '';
    DECLARE CONT INT DEFAULT 1;
    DECLARE PARES INT DEFAULT 2;
    DECLARE IMPARES INT DEFAULT 1;

   WHILE CONT <= LIMITE DO
       IF CONT % 2 = 1 THEN
           SET RESP = CONCAT(RESP,PARES,',');
            SET PARES = PARES + 2;
       ELSE
           SET RESP = CONCAT(RESP,IMPARES,',');
       SET IMPARES = IMPARES + 2;
           END IF;
    SET CONT = CONT +1;
    end while;
    RETURN RESP;
end;
SELECT NUMEROSNATURALESV4(10)